# Site settings
title:          foldir xyz
description:    "foldir.xyz adalah blog pribadi."
baseurl:        ""
url:            "https://foldir.xyz"
timezone: Asia/Jakarta

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         wildan hidayat
  url:          https://foldir.xyz
  email:        https://foldir.xyz

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
