# ------------------------
# Site settings
# ------------------------
title:          foldir xyz
description:    "foldir.xyz adalah blog pribadi berisi catatan bermanfaat, islami, teknologi, dan kehidupan sehari-hari."
baseurl:        "" # Kosongkan jika di root domain
url:            "https://foldir.xyz"
timezone:       Asia/Jakarta
lang:           id

# ------------------------
# Google Analytics
# ------------------------
google_analytics: GTM-MDLLG3RZ # Jika pakai GA4, masukkan gtag manual di layout

# ------------------------
# Author Info
# ------------------------
author:
  name:         Wildan Hidayat
  url:          https://foldir.xyz
  email:        your@email.com

# ------------------------
# SEO Defaults & Social
# ------------------------
defaults:
  - scope:
      path: ""
    values:
      image: /assets/apple-touch-icon.webp  # Thumbnail default untuk semua halaman
      twitter:
        username: "@foldir_xyz"  # Opsional: jika punya akun Twitter
social:
  name: foldir xyz
  links:
    - https://twitter.com/foldir_xyz

# ------------------------
# Build Settings
# ------------------------
markdown:       kramdown
kramdown:
  input: GFM
include:
  - _pages

# ------------------------
# Assets / SASS
# ------------------------
sass:
  sass_dir:     _sass
  style:        compressed

# ------------------------
# Plugins
# ------------------------
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jemoji

# ------------------------
# Permalinks & Pagination
# ------------------------
permalink:      /:title
paginate:       5

# ------------------------
# Exclude (file tidak ikut publish)
# ------------------------
exclude:
  - Gemfile
  - Gemfile.lock
  - tale.gemspec
  - README.md
  - .gitignore
  - node_modules
  - vendor

# ------------------------
# Disqus Comment System
# ------------------------
disqus:         foldir-xzy

# ------------------------
# Misc Settings
# ------------------------
lsi: false
strict_front_matter: true
