# ------------------------
# Site settings
# ------------------------
title:          foldir xyz
description:    "foldir.xyz adalah blog pribadi"
baseurl:        "" # Jangan diisi jika di root domain
url:            "https://foldir.xyz"
timezone:       Asia/Jakarta

# ------------------------
# Google Analytics
# ------------------------
google_analytics: UA-XXXXXXXX-X # (jika sudah pakai GA4, gunakan gtag script manual di layout)

# ------------------------
# Author Info
# ------------------------
author:
  name:         Wildan Hidayat
  url:          https://foldir.xyz
  email:        your@email.com # Bukan URL ya, isi alamat email asli

# ------------------------
# Build Settings
# ------------------------
markdown:       kramdown
include:
  - _pages

# ------------------------
# Assets / SASS
# ------------------------
sass:
  sass_dir:     _sass
  style:        compressed

# ------------------------
# Plugins
# ------------------------
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jemoji # Un-comment untuk aktifkan emoji di markdown

# ------------------------
# Permalinks & Pagination
# ------------------------
permalink:      /:title/
paginate:       5

# ------------------------
# Exclude (file tidak ikut publish)
# ------------------------
exclude:
  - Gemfile
  - Gemfile.lock
  - tale.gemspec
  - README.md
  - .gitignore
  - node_modules
  - vendor

# ------------------------
# Disqus Comment System
# ------------------------
disqus:         foldirxyz # Ganti dengan ID Disqus milikmu yang benar
lsi: false
strict_front_matter: true
