name: Generate Sitemap

on:
  push:
    branches:
      - main  # Jalankan hanya saat ada push ke branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Sitemap Generator
        run: npm install -g sitemap-generator-cli

      - name: Generate Sitemap
        run: sitemap-generator https://foldirku.github.io/7584./sitemap.xml

      - name: Commit and Push Sitemap
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add sitemap.xml
          git commit -m "🔄 Update sitemap automatically"
          git push
