name: Autoblog Harian

on:
  schedule:
    - cron: "5 0 * * *"  # Setiap hari jam 08:00 pagi WIB
  workflow_dispatch:

jobs:
  autoblog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Generate Artikel
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: node generate-article.js

    - name: Commit & Push
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add artikel-*.html
        git commit -m "📝 Artikel AI: $(date +'%Y-%m-%d')" || echo "Tidak ada perubahan"
        git push
