name: Build Static Sitemap Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run sitemap page builder
        run: node scripts/build-index.js

      - name: Commit built pages
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add index.html page*.html
          git commit -m "Auto-generate paginated index from sitemap" || echo "No changes"
          git push
