name: Generate Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # penting agar git log bisa baca seluruh riwayat

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Generate sitemap.xml
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml

          for file in $(find . -name "*.html" | sort); do
            cleanpath="${file#./}"
            url="https://foldir.xyz/${cleanpath}"
            lastmod=$(git log -1 --format="%cI" "$file" 2>/dev/null || date -I)
            echo "  <url>" >> sitemap.xml
            echo "    <loc>$url</loc>" >> sitemap.xml
            echo "    <lastmod>$lastmod</lastmod>" >> sitemap.xml
            echo "  </url>" >> sitemap.xml
          done

          echo '</urlset>' >> sitemap.xml

      - name: Commit and push sitemap.xml
        run: |
          git add sitemap.xml
          git commit -m "Update sitemap.xml with accurate lastmod" || echo "No changes"
          git push origin main
