name: Generate Artikel Harian Otomatis

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install jq -y

      - name: Generate 1 artikel per hari
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          mkdir -p artikel

          readarray -t topik_array < data/topik.txt
          first_topic="${topik_array[0]}"

          if [ -z "$first_topic" ]; then
            echo "Tidak ada topik tersisa di data/topik.txt"
            exit 0
          fi

          slug=$(echo "$first_topic" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd 'a-z0-9\-')
          output="artikel/$slug.html"

          if [ -f "$output" ]; then
            echo "Topik sudah pernah dibuat: $output"
            exit 0
          fi

          response=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "$(cat <<JSON
          {
          \"model\": \"gpt-4-turbo\",
          \"messages\": [
          {
          \"role\": \"system\",
          \"content\": \"Kamu adalah penulis artikel profesional. Tulis artikel SEO dalam bahasa Indonesia dengan panjang minimal 800 kata. Gunakan struktur HTML dengan <h2>, <p>, dan penutup. Hindari artikel pendek atau terlalu umum. Artikel harus relevan dan menarik.\"
          },
          {
          \"role\": \"user\",
          \"content\": \"Tulis artikel dengan topik: $first_topic\"
          }
          ]
          }
          JSON
            )")

          konten=$(echo "$response" | jq -r '.choices[0].message.content')
          word_count=$(echo "$konten" | wc -w)

          if [ "$word_count" -lt 300 ]; then
            echo "Artikel terlalu pendek ($word_count kata), tidak akan disimpan."
            exit 0
          fi

          deskripsi=$(echo "$konten" | grep -o '<p>.*</p>' | head -n 1 | sed 's/<[^>]*>//g' | cut -c1-160)

          echo "<!DOCTYPE html>" > "$output"
          echo "<html lang=\"id\">" >> "$output"
          echo "<head>" >> "$output"
          echo "  <meta charset=\"UTF-8\" />" >> "$output"
          echo "  <title>$first_topic</title>" >> "$output"
          echo "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />" >> "$output"
          echo "  <meta name=\"description\" content=\"$deskripsi\">" >> "$output"
          echo "</head>" >> "$output"
          echo "<body>" >> "$output"
          echo "  <article>" >> "$output"
          echo "    <h1>$first_topic</h1>" >> "$output"
          echo "    <img src=\"https://source.unsplash.com/800x400/?$slug\" alt=\"$first_topic\" style=\"width:100%;max-height:400px;object-fit:cover;border-radius:12px;margin-bottom:20px;\">" >> "$output"
          echo "$konten" >> "$output"
          echo "  </article>" >> "$output"
          echo "</body>" >> "$output"
          echo "</html>" >> "$output"

          printf "%s\n" "${topik_array[@]:1}" > data/topik.txt

      - name: Ping Google Sitemap
        run: |
          curl "https://www.google.com/ping?sitemap=https://foldir.xyz/sitemap.xml"

      - name: Commit dan Push
        run: |
          git add artikel/ data/topik.txt
          git commit -m "Generate artikel harian: $first_topic" || echo "Tidak ada perubahan"
          git push origin main
