name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate sitemap.xml
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="https://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          
          base_url="https://foldirku.github.io/7584"

          for file in $(find . -name "*.html" -not -path "./.*"); do
            clean_path=$(echo "$file" | sed 's|^\./||')
            url="${base_url}/${clean_path}"
            lastmod=$(date -u +"%Y-%m-%d")
            echo "  <url>" >> sitemap.xml
            echo "    <loc>${url}</loc>" >> sitemap.xml
            echo "    <lastmod>${lastmod}</lastmod>" >> sitemap.xml
            echo "    <changefreq>monthly</changefreq>" >> sitemap.xml
            echo "    <priority>0.5</priority>" >> sitemap.xml
            echo "  </url>" >> sitemap.xml
          done

          echo '</urlset>' >> sitemap.xml

      - name: Commit and push sitemap.xml
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add sitemap.xml
          git commit -m "Auto-update sitemap.xml" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
