name: Scheduled Build
on:
  schedule:
    - cron: "23 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Touch file (to trigger rebuild)
        run: |
          date >> .rebuild.log
          git add .rebuild.log
          git commit -m "Scheduled rebuild" || echo "Nothing to commit"

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
